### ISSUE TITLE
insufficient usage instructions for someone unfamiliar with Lisp IDEs

### ISSUE THREAD

**Issue by Lx** [mchung94/pyramid-solver#1]
I'm keen to try this project, but even with a computing background I'm struggling to get started.

I've downloaded LispWorks Personal Edition, and immediately I'm stuck at entering the line from the README:

```
(asdf:load-system "pyramid-solver")
```

The only obvious location to enter this line is the Listener window, which then has this to say:

```
Error: Reader cannot find package ASDF.
  1 (continue) Create the ASDF package.
  2 Use another package instead of ASDF.
  3 Try finding package ASDF again.
  4 (abort) Return to level 0.
  5 Return to top loop level 0.
```

This makes sense since the README also states that ASDF is an external requirement, so with [information from the LispWorks User Guide](http://www.lispworks.com/documentation/lw61/LW/html/lw-311.htm) I tried entering this:

```
(require "asdf")
(asdf:load-system "pyramid-solver")
```

but then I got this in response:

```
Error: Component "pyramid-solver" not found
  1 (continue) Retry finding system pyramid-solver after reinitializing
               the source-registry.
  2 (abort) Return to level 1.
  3 Return to debug level 1.
  4 Return to level 0.
  5 Return to top loop level 0.
```

which prompted me to try this instruction from the README:

> * If you want to, you can remove the (in-package #:pyramid-solver) from src/pyramid-solver.lisp and load that file on its own.

which resulted in this error message appearing:

```
Reader cannot find package PS.
```

and with no such similar requirement appearing in the Requirements section of the README, I'm at a loss as to how to continue.

Would you please consider enhancing the usage instructions for someone who doesn't have Lisp experience, or linking to a tutorial resource that will give someone enough guidance to get your project working in LispWorks, and/or just provide a compiled binary?

**Comment by mchung94** [comment]
Thanks for the feedback and I'm sorry the instructions weren't clear.

There's a compiled executable for Windows at [pyramid-solver-1.2.0.zip](https://github.com/mchung94/pyramid-solver/releases/download/v1.2.0/pyramid-solver-1.2.0.zip) on the releases page: https://github.com/mchung94/pyramid-solver/releases/tag/v1.2.0

Unfortunately, LispWorks Personal Edition won't work with this program because of its heap size limit - it'll run into the memory usage limit and exit.

I'll work on some fixes and updates to the documentation to help.

**Comment by mchung94** [comment]
I'm going to add some instructions to the README and recommend using SBCL instead of LispWorks Personal Edition, but I thought it might be helpful for you if I explain what happened:

When it showed the error `Reader cannot find package PS.` when trying to load the pyramid-solver.lisp file, that was a mistake in my code and I'll have the fix right after I post this.

LispWorks showed the `Error: Component "pyramid-solver" not found` message because ASDF did not know where to find the pyramid-solver source code.  So if the code was in `C:/github/pyramid-solver/`, the next step in the Listener would be to type `(push "C:/github/pyramid-solver/" asdf:*central-registry*)`. The last slash at the end of pyramid-solver is required.

LispWorks Personal Edition uses an old version of ASDF, so the next error would have been `Error: Reader cannot find package UIOP.`  The latest [ASDF](https://common-lisp.net/project/asdf/) is at [asdf.lisp](https://common-lisp.net/project/asdf/archives/asdf.lisp), and you can load that first instead of running `(require "asdf")` - then `(asdf:load-system "pyramid-solver")` would work.  At that point it would compile but run out of memory when trying to solve a game.

So my recommendations are to do one of the following options:
1. If you are okay with running the compiled binary, there's one for Windows at [pyramid-solver-1.2.0.zip](https://github.com/mchung94/pyramid-solver/releases/download/v1.2.0/pyramid-solver-1.2.0.zip)
2. LispWorks Personal Edition has memory usage limits so it won't work for this program, but [SBCL](http://www.sbcl.org/platform-table.html) works when running `sbcl --dynamic-space-size 8192`.  Then you can run:
   - `(require "asdf")`
   - `(push "C:/github/pyramid-solver/" asdf:*central-registry*)` replacing C:/github/pyramid-solver/ with the actual directory the source code is in.
   - `(asdf:load-system "pyramid-solver")`
   - `(ps:solve (ps:string->card-list "6d 5h Ah Jd 4s Ks 6s 8c 2h 4d 9s Kd 6c Ad 8s Ac 5c 9d 7h 3h 8d 5s 4c Qc Jh Kc Kh 3c 3s 9c As 5d Qh Ts 4h 7s Td 9h Th 7c 8h 2c 7d Tc 2d 6h 2s Js Qd 3d Qs Jc"))`
3. Or after my next update you can remove the first line from `src/pyramid-solver.lisp` and load that file on its own without problems.

**Comment by Lx** [comment]
Thank you for the excellent follow-up.  I failed to notice the available pre-compiled release.

I'm keen to get this working in Lisp and get a better understanding of your source code, so the additional information you provided is really useful.  I appreciate your time & efforts.
